import { BaseExpert, type ExpertResult, type ExpertContext } from './base-expert.js';
import type { Task } from '../planner/task-splitter.js';
import { writeText } from '../utils/fs-utils.js';
import * as path from 'node:path';

/**
 * 动态专家配置
 */
export interface DynamicExpertConfig {
  name: string;
  canHandlePattern: {
    types?: string[];
    expertName?: string;
  };
  codeGenerator: {
    fileExtensions: string[];
    template: (name: string, task: Task) => string;
  };
}

/**
 * 动态专家生成器
 * 允许根据配置动态创建专家
 */
export class DynamicExpert extends BaseExpert {
  private config: DynamicExpertConfig;

  constructor(context: ExpertContext, config: DynamicExpertConfig) {
    super(config.name, context);
    this.config = config;
  }

  canHandle(task: Task): boolean {
    // 检查任务类型匹配
    if (this.config.canHandlePattern.types?.includes(task.type)) {
      return true;
    }
    // 检查专家名称匹配
    if (this.config.canHandlePattern.expertName && 
        task.expert === this.config.canHandlePattern.expertName) {
      return true;
    }
    return false;
  }

  async execute(task: Task): Promise<ExpertResult> {
    this.log(`执行任务: ${task.name}`);

    const files: string[] = [];
    const changes: ExpertResult['changes'] = [];

    for (const filePath of task.output.files) {
      const fullPath = path.join(this.getProjectRoot(), filePath);
      const code = await this.generateCode(task, filePath);

      await writeText(fullPath, code);
      files.push(fullPath);
      changes.push({
        file: filePath,
        operation: 'create',
        description: `创建 ${task.name}`,
      });
    }

    const verification = await this.selfCheck(task, files);

    return {
      success: verification.passed,
      files,
      changes,
      verification,
    };
  }

  private async generateCode(task: Task, filePath: string): Promise<string> {
    const ext = path.extname(filePath);
    const name = path.basename(filePath, ext);

    // 检查文件扩展名是否匹配配置
    if (this.config.codeGenerator.fileExtensions.includes(ext)) {
      return this.config.codeGenerator.template(name, task);
    }

    return `// ${task.name}\n// Auto-generated by ${this.name}\n`;
  }

  private async selfCheck(task: Task, files: string[]): Promise<{ passed: boolean; message: string }> {
    // 简化版自检：检查文件是否存在
    for (const file of files) {
      try {
        const { fileExists } = await import('../utils/fs-utils.js');
        if (!(await fileExists(file))) {
          return { passed: false, message: `文件 ${file} 未创建成功` };
        }
      } catch {
        return { passed: false, message: `无法验证文件 ${file}` };
      }
    }

    return { passed: true, message: '自检通过' };
  }
}

/**
 * 动态专家工厂
 * 用于创建和管理动态专家
 */
export class DynamicExpertFactory {
  private context: ExpertContext;

  constructor(context: ExpertContext) {
    this.context = context;
  }

  /**
   * 根据配置创建动态专家
   */
  create(config: DynamicExpertConfig): DynamicExpert {
    return new DynamicExpert(this.context, config);
  }

  /**
   * 创建测试专家
   */
  createTestExpert(): DynamicExpert {
    return this.create({
      name: 'TestExpert',
      canHandlePattern: {
        types: ['test'],
        expertName: 'TestExpert',
      },
      codeGenerator: {
        fileExtensions: ['.test.ts', '.spec.ts', '.test.js', '.spec.js'],
        template: (name: string, task: Task) => {
          return `import { describe, it, expect } from 'vitest';

/**
 * ${task.description}
 */
describe('${name}', () => {
  it('should pass', () => {
    // TODO: 实现测试用例
    expect(true).toBe(true);
  });
});
`;
        },
      },
    });
  }

  /**
   * 创建配置专家
   */
  createConfigExpert(): DynamicExpert {
    return this.create({
      name: 'ConfigExpert',
      canHandlePattern: {
        types: ['config'],
        expertName: 'ConfigExpert',
      },
      codeGenerator: {
        fileExtensions: ['.json', '.yaml', '.yml', '.toml', '.ini'],
        template: (name: string, task: Task) => {
          return `# ${task.description}
# Auto-generated by ConfigExpert
`;
        },
      },
    });
  }
}
