import { BaseExpert, type ExpertResult } from './base-expert.js';
import type { Task } from '../planner/task-splitter.js';
import { writeText } from '../utils/fs-utils.js';
import * as path from 'node:path';

export class FrontendExpert extends BaseExpert {
  constructor(context: any) {
    super('FrontendExpert', context);
  }

  canHandle(task: Task): boolean {
    return task.type === 'component' || task.type === 'style' || 
           task.expert === 'FrontendExpert';
  }

  async execute(task: Task): Promise<ExpertResult> {
    this.log(`执行任务: ${task.name}`);

    const files: string[] = [];
    const changes: ExpertResult['changes'] = [];

    for (const filePath of task.output.files) {
      const fullPath = path.join(this.getProjectRoot(), filePath);
      const code = await this.generateCode(task, filePath);

      await writeText(fullPath, code);
      files.push(fullPath);
      changes.push({
        file: filePath,
        operation: 'create',
        description: `创建 ${task.name}`,
      });
    }

    // 自检
    const verification = await this.selfCheck(task, files);

    return {
      success: verification.passed,
      files,
      changes,
      verification,
      suggestions: verification.passed ? undefined : ['请检查生成的代码'],
    };
  }

  private async generateCode(task: Task, filePath: string): Promise<string> {
    const ext = path.extname(filePath);
    const name = path.basename(filePath, ext);

    if (ext === '.tsx' || ext === '.jsx') {
      return this.generateReactComponent(name, task);
    }

    if (ext === '.vue') {
      return this.generateVueComponent(name, task);
    }

    if (ext === '.scss' || ext === '.css') {
      return this.generateStyles(name);
    }

    return `// ${task.name}\n// Auto-generated by dev-flow\n`;
  }

  private generateReactComponent(name: string, task: Task): string {
    return `import React from 'react';

interface ${name}Props {
  // TODO: 定义props
}

export const ${name}: React.FC<${name}Props> = () => {
  return (
    <div className="${name.toLowerCase()}">
      {/* ${task.description} */}
    </div>
  );
};

export default ${name};
`;
  }

  private generateVueComponent(name: string, task: Task): string {
    return `<template>
  <div class="${name.toLowerCase()}">
    <!-- ${task.description} -->
  </div>
</template>

<script setup lang="ts">
// TODO: 实现组件逻辑
</script>

<style scoped>
.${name.toLowerCase()} {
  /* 样式 */
}
</style>
`;
  }

  private generateStyles(name: string): string {
    return `.${name.toLowerCase()} {
  /* 样式定义 */
}
`;
  }

  private async selfCheck(task: Task, files: string[]): Promise<{ passed: boolean; message: string }> {
    // 简化版自检：检查文件是否存在
    for (const file of files) {
      try {
        const { fileExists } = await import('../utils/fs-utils.js');
        if (!(await fileExists(file))) {
          return { passed: false, message: `文件 ${file} 未创建成功` };
        }
      } catch {
        return { passed: false, message: `无法验证文件 ${file}` };
      }
    }

    return { passed: true, message: '自检通过' };
  }
}
